spring:
  datasource:
    url: jdbc:mysql://localhost:3306/post_db
    username: root
    password: pass1234

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true